name: Test_app
# this is a comment
on:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: Windows
    steps:
      - uses: actions/checkout@v3
      - name: manual approve
        run: |
            echo "Manually approved"
