name: Test_app
# this is a comment
on:
  workflow_dispatch:
   inputs:
    targetenv:
     type: choice
     description : select the environment
     options:
      - D1staging
      - D1prod
      - vfint
      - vfprod
  
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: manual approve
        run: |
            echo "Manually approved to run on ${{ github.event.inputs.targetenv }} "
            echo " the MES300 URL for this repo is ${{ vars.MES300URL }} "
